/**
 * GET /api/analyze/mask/[analysisId]
 *
 * Securely serves the localization overlay PNG generated by the FastAPI ML backend.
 *
 * Security model:
 *   - Clerk authentication enforced — unauthenticated requests rejected.
 *   - The overlay filesystem path is read from MongoDB (not from the URL/query).
 *   - The resolved path is validated to be inside the ml_backend/outputs/ directory
 *     to prevent path traversal attacks.
 *   - The analysisId must belong to the authenticated user.
 *   - No arbitrary file on the server can be accessed via this endpoint.
 */
import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";
import { connectToDatabase } from "@/lib/mongodb";
import Analysis from "@/models/Analysis";

/**
 * Absolute path to the ml_backend/outputs directory.
 * All overlay/mask files must be inside this directory.
 */
const OUTPUTS_ROOT = path.resolve(
  process.cwd(),
  "ml_backend",
  "outputs"
);

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ analysisId: string }> }
) {
  // 1. Authenticate
  const { userId } = await auth();
  if (!userId) {
    return new NextResponse("Unauthorized", { status: 401 });
  }

  const { analysisId } = await params;

  // 2. Validate analysisId format (MongoDB ObjectId: 24 hex chars)
  if (!/^[0-9a-fA-F]{24}$/.test(analysisId)) {
    return new NextResponse("Invalid analysisId", { status: 400 });
  }

  // 3. Look up the record in MongoDB
  await connectToDatabase();
  const record = await Analysis.findById(analysisId).select(
    "clerkUserId overlayPath maskPath status"
  );

  if (!record) {
    return new NextResponse("Analysis not found", { status: 404 });
  }

  // 4. Ownership check
  if (record.clerkUserId !== userId) {
    return new NextResponse("Forbidden", { status: 403 });
  }

  // 5. Check requested asset (default: overlay; ?type=mask: binary mask)
  const { searchParams } = new URL(_req.url);
  const isMask = searchParams.get("type") === "mask";
  const targetPath: string | undefined | null = (
    isMask ? record.maskPath : record.overlayPath
  ) as string | undefined | null;

  if (!targetPath) {
    return new NextResponse(
      `${isMask ? "Mask" : "Overlay"} not available for this analysis`,
      { status: 404 }
    );
  }

  // 6. Path traversal guard — resolve and confirm it is inside OUTPUTS_ROOT
  const resolvedPath = path.resolve(targetPath);
  if (!resolvedPath.startsWith(OUTPUTS_ROOT + path.sep) &&
      !resolvedPath.startsWith(OUTPUTS_ROOT + "/") &&
      resolvedPath !== OUTPUTS_ROOT) {
    console.error(
      "[mask] Path traversal attempt blocked. targetPath=%s resolvedPath=%s OUTPUTS_ROOT=%s",
      targetPath,
      resolvedPath,
      OUTPUTS_ROOT
    );
    return new NextResponse("Forbidden", { status: 403 });
  }

  // 7. Read and stream the file
  try {
    const fileBytes = await readFile(resolvedPath);
    return new NextResponse(fileBytes, {
      status: 200,
      headers: {
        "Content-Type": "image/png",
        // Cache for 1 hour — overlay is immutable once generated
        "Cache-Control": "private, max-age=3600, immutable",
        "Content-Length": String(fileBytes.byteLength),
      },
    });
  } catch (err: unknown) {
    const isNotFound =
      err instanceof Error &&
      "code" in err &&
      (err as NodeJS.ErrnoException).code === "ENOENT";
    if (isNotFound) {
      return new NextResponse("Overlay file not found on server", {
        status: 404,
      });
    }
    console.error("[mask] Failed to read overlay file:", err);
    return new NextResponse("Failed to read overlay file", { status: 500 });
  }
}
